ERROR:ex:[Errno 2] No such file or directory: '~/Documents/1200px-Hamster_057eue.jpg'
Traceback (most recent call last):
  File "/var/www/photomosaic/photomosaic/routes.py", line 64, in upload_file
    f.save('~/Documents/' + filename)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '~/Documents/1200px-Hamster_057eue.jpg'
ERROR:ex:[Errno 2] No such file or directory: '~/Documents/1200px-Hamster_057eue.jpg'
Traceback (most recent call last):
  File "/var/www/photomosaic/photomosaic/routes.py", line 64, in upload_file
    f.save('~/Documents/' + filename)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '~/Documents/1200px-Hamster_057eue.jpg'
